spring:
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url:  jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    enabled: true
    user: sa
    password:
    url:  jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    change-log: classpath:/db/master.yaml
server:
  port: 8080